<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
    <PackageReference Include="Radzen.Blazor" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\PlannerCRM.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\Bootstrap\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\person.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\Forms\EmployeeForm.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

</Project>
