// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlannerCRM.Server.DataAccess;

#nullable disable

namespace PlannerCRM.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "roles", new[] { "account_manager", "operation_manager", "project_manager", "senior_developer", "junior_developer" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActivityEmployee", b =>
                {
                    b.Property<Guid>("ActivitiesGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeesGuid")
                        .HasColumnType("uuid");

                    b.HasKey("ActivitiesGuid", "EmployeesGuid");

                    b.HasIndex("EmployeesGuid");

                    b.ToTable("ActivityEmployee");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Activity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnd")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.EmployeeLoginData", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeLoginData");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.FirmClient", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("VatNumber")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Salary", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirmClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderCostId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("FirmClientId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.WorkOrderCost", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FirmClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("FirmClientId");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("WorkOrderCosts");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.WorkTime", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("WorkedHours")
                        .HasColumnType("double precision");

                    b.HasKey("Guid");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkTimes");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.ActivityWorkTime", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkTimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("ActivityId");

                    b.HasIndex("WorkTimeId");

                    b.ToTable("ActivityWorkTimes");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.ClientWorkOrder", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("ClientWorkOrders");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.ClientWorkOrderCost", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirmClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderCostId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("FirmClientId");

                    b.HasIndex("WorkOrderCostId");

                    b.ToTable("ClientWorkOrderCosts");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeActivity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeActivities");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeRole", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeSalary", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SalaryId");

                    b.ToTable("EmployeeSalaries");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeWorkTime", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkTimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WorkTimeId");

                    b.ToTable("EmployeeWorkTimes");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.WorkOrderActivity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("ActivityId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderActivities");
                });

            modelBuilder.Entity("ActivityEmployee", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Activity", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Activities")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.EmployeeLoginData", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany("LoginData")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Salary", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.WorkOrder", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.FirmClient", "FirmClient")
                        .WithMany("WorkOrders")
                        .HasForeignKey("FirmClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirmClient");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.WorkOrderCost", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.FirmClient", "FirmClient")
                        .WithMany("WorkOrderCosts")
                        .HasForeignKey("FirmClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.WorkOrder", "WorkOrder")
                        .WithOne("WorkOrderCost")
                        .HasForeignKey("PlannerCRM.Server.Models.Entities.WorkOrderCost", "WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirmClient");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.WorkTime", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany("WorkTimes")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Employee");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.ActivityWorkTime", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Activity", "Activity")
                        .WithMany("ActivityWorkTimes")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.WorkTime", "WorkTime")
                        .WithMany("ActivityWorkTimes")
                        .HasForeignKey("WorkTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("WorkTime");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.ClientWorkOrderCost", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.FirmClient", "FirmClient")
                        .WithMany()
                        .HasForeignKey("FirmClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.WorkOrderCost", "WorkOrderCost")
                        .WithMany()
                        .HasForeignKey("WorkOrderCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirmClient");

                    b.Navigation("WorkOrderCost");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeActivity", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Activity", "Activity")
                        .WithMany("EmployeeActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany("EmployeeActivities")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeRole", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeSalary", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.Salary", "Salary")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("SalaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Salary");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeWorkTime", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.WorkTime", "WorkTime")
                        .WithMany()
                        .HasForeignKey("WorkTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("WorkTime");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.WorkOrderActivity", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Activity", b =>
                {
                    b.Navigation("ActivityWorkTimes");

                    b.Navigation("EmployeeActivities");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeActivities");

                    b.Navigation("EmployeeRoles");

                    b.Navigation("EmployeeSalaries");

                    b.Navigation("LoginData");

                    b.Navigation("Salaries");

                    b.Navigation("WorkTimes");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.FirmClient", b =>
                {
                    b.Navigation("WorkOrderCosts");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Role", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Salary", b =>
                {
                    b.Navigation("EmployeeSalaries");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.WorkOrder", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("WorkOrderCost");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.WorkTime", b =>
                {
                    b.Navigation("ActivityWorkTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
