// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlannerCRM.Server.DataAccess;

#nullable disable

namespace PlannerCRM.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "roles", new[] { "account_manager", "operation_manager", "project_manager", "senior_developer", "junior_developer" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActivityEmployee", b =>
                {
                    b.Property<Guid>("ActivitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeesId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivitiesId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("ActivityEmployee");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Activity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("workOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("workOrderId");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnd")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.firmClient", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("vatNumber")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("roleName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.workOrder", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("firmClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("workOrderCostId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("firmClientId");

                    b.ToTable("workOrders");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.ClientWorkOrder", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("firmClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("workOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.ToTable("ClientWorkOrders");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeActivity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("activityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("employeeId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("activityId");

                    b.HasIndex("employeeId");

                    b.ToTable("EmployeeActivities");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeRole", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("employeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("roleId")
                        .HasColumnType("uuid");

                    b.Property<string>("roleName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("employeeId");

                    b.HasIndex("roleId");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.WorkOrderActivity", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("activityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("workOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("activityId");

                    b.HasIndex("workOrderId");

                    b.ToTable("WorkOrderActivities");
                });

            modelBuilder.Entity("ActivityEmployee", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Activity", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.workOrder", "workOrder")
                        .WithMany("activities")
                        .HasForeignKey("workOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("workOrder");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.workOrder", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.firmClient", "firmClient")
                        .WithMany("workOrders")
                        .HasForeignKey("firmClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("firmClient");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeActivity", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Activity", "Activity")
                        .WithMany("EmployeeActivities")
                        .HasForeignKey("activityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany("EmployeeActivities")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.EmployeeRole", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.JoinEntities.WorkOrderActivity", b =>
                {
                    b.HasOne("PlannerCRM.Server.Models.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("activityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlannerCRM.Server.Models.Entities.workOrder", "workOrder")
                        .WithMany()
                        .HasForeignKey("workOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("workOrder");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Activity", b =>
                {
                    b.Navigation("EmployeeActivities");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeActivities");

                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.firmClient", b =>
                {
                    b.Navigation("workOrders");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.Role", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("PlannerCRM.Server.Models.Entities.workOrder", b =>
                {
                    b.Navigation("activities");
                });
#pragma warning restore 612, 618
        }
    }
}
