global using System.ComponentModel.DataAnnotations;
global using static PlannerCRM.Shared.Constants.ConstantValues;
global using PlannerCRM.Shared.Models;
global using System.Text.RegularExpressions;
global using PlannerCRM.Shared.DTOs.ActivityDto.Forms;
global using PlannerCRM.Shared.DTOs.EmployeeDto.Forms;
global using PlannerCRM.Shared.Attributes;
global using PlannerCRM.Shared.DTOs.ActivityDto.Views;
global using PlannerCRM.Shared.DTOs.EmployeeDto.Views;
global using PlannerCRM.Shared.DTOs.WorkOrder.Views;